# Meta-analysis configuration for Mountain Car environment

[meta_analysis]
# Parameter ranges for force and friction
# Force range: Controls the engine force limit
min_force = 0.01    # Minimum engine force limit
max_force = 0.09    # Maximum engine force limit
force_steps = 3     # Number of force values to test

# Friction range: Controls the friction coefficient
min_friction = 0.01  # Minimum friction coefficient
max_friction = 0.09  # Maximum friction coefficient
friction_steps = 3   # Number of friction values to test

[simulation]
# Simulation parameters
n_episodes = 2       # Number of episodes per parameter combination
max_steps = 200      # Maximum steps per episode
planning_horizon = 30 # Planning horizon for Active Inference agent

[initial_state]
# Initial state configuration
position = -0.5      # Starting position of the car
velocity = 0.0       # Starting velocity of the car

[target_state]
# Target state configuration
position = 0.5       # Target position to reach
velocity = 0.0       # Target velocity at goal

[visualization]
# Visualization settings
plot_width = 100     # Width of plots in characters
plot_height = 30     # Height of plots in characters
plot_colormap = "viridis"  # Colormap for heatmaps
plot_border = "ascii"      # Border style for plots

[output]
# Output settings
save_trajectories = true   # Save individual trajectory data
save_raw_data = true      # Save raw simulation results
compress_results = false   # Compress output files