# Mountain Car Simulation Configuration

[physics]
engine_force_limit = 0.04 
friction_coefficient = 0.1 

[initial_state]
position = -0.5     # Starting position in the valley
velocity = 0.0      # Starting velocity

[target_state]
position = 0.5      # Target position
velocity = 0.0      # Target velocity

[simulation]
timesteps = 200            # Total simulation time for both approaches
planning_horizon = 30      # Planning horizon for active inference

[model_parameters]
state_transition_precision = 1e4  # Gamma parameter (precision of state transitions)
observation_precision = 1e-4      # Theta parameter (precision of observations)
belief_uncertainty_huge = 1e10    # Large uncertainty value for beliefs
belief_uncertainty_tiny = 1e-10   # Small uncertainty value for beliefs

[visualization]
fps = 15                     # Frames per second for animations
landscape_xlims = [-1.0, 1.0]  # X-axis limits for landscape plot
landscape_ylims = [-0.05, 0.15] # Y-axis limits for landscape plot 

[parameter_sweep]
n_force = 5                # Number of engine force values to test
n_friction = 5            # Number of friction values to test
force_min = 0.01          # Minimum engine force limit
force_max = 0.2           # Maximum engine force limit
friction_min = 0.01       # Minimum friction coefficient
friction_max = 0.2        # Maximum friction coefficient

[meta_analysis]
timesteps = 300           # Number of timesteps for each simulation
planning_horizon = 30     # Planning horizon for active inference
position_threshold = 0.01 # Position threshold for target achievement
velocity_threshold = 0.05 # Velocity threshold for target achievement
num_workers = 4          # Number of worker processes to use (default: number of threads)
save_trajectories = true # Whether to save full trajectory data
plot_dpi = 300          # DPI for output plots
plot_size = [800, 600]  # Default plot size [width, height]