# Meta-analysis configuration for Mountain Car environment

[meta_analysis]
# Parameter ranges for force and friction
# Force range: Controls the engine force limit
min_force = 0.01    # Minimum engine force limit
max_force = 0.21    # Maximum engine force limit
force_steps = 10     # Number of force values to test

# Friction range: Controls the friction coefficient
min_friction = 0.01  # Minimum friction coefficient
max_friction = 0.21  # Maximum friction coefficient
friction_steps = 10   # Number of friction values to test

[simulation]
# Simulation parameters
n_episodes = 1       # Number of episodes per parameter combination
max_steps = 100      # Maximum steps per episode
planning_horizon = 40 # Planning horizon for Active Inference agent

[initial_state]
# Initial state configuration
position = -0.5      # Starting position of the car (standard starting point)
velocity = 0.0       # Starting velocity of the car (start from rest)

[target_state]
# Target state configuration
position = 0.5       # Target position to reach (standard goal position)
velocity = 0.0       # Target velocity at goal (stop at goal)

[visualization]
# Visualization settings
plot_width = 150     # Width of plots in characters (increased for better readability)
plot_height = 50     # Height of plots in characters (increased for better detail)
plot_colormap = "viridis"  # Colormap for heatmaps (perceptually uniform colormap)
plot_border = "ascii"      # Border style for plots (compatible with all terminals)

[output]
# Output settings
save_trajectories = true   # Save individual trajectory data for detailed analysis
save_raw_data = true      # Save raw simulation results for future reference
compress_results = false   # Keep results uncompressed for easier inspection