# Configuration for Mountain Car Meta-Analysis

# Simulation parameters
simulation:
  timesteps: 200  # Maximum timesteps per simulation
  n_repetitions: 3  # Number of repetitions per parameter combination

# Initial state
initial_state:
  position: -0.5  # Starting position
  velocity: 0.0   # Starting velocity

# Target state
target_state:
  position: 0.5   # Target position
  velocity: 0.0   # Target velocity

# Meta-analysis parameters
meta_analysis:
  force:
    min: 0.001    # Minimum engine force
    max: 0.05    # Maximum engine force
    steps: 3      # Number of force values to test
  
  friction:
    min: 0.0001   # Minimum friction coefficient
    max: 0.05   # Maximum friction coefficient
    steps: 3      # Number of friction values to test

# Logging configuration
logging:
  level: "Info"   # Logging level (Debug, Info, Warn, Error)
  file: true      # Whether to save logs to file
  console: true   # Whether to show logs in console

# Output configuration
output:
  save_trajectories: true  # Whether to save full trajectories
  plot_format: "png"       # Format for plot outputs
  dpi: 300                 # DPI for plot outputs 